### PR TITLE
Update data.py

### PR DESCRIPTION
**Pull request by alexanderthebadatcoding**
fix date checker.

### CODE REVIEW

**Comment by m0ranwad** [comment]
@alexanderthebadatcoding - as far as I can tell, this is a breaking change for the displaying the Countdown. 

Prior to this change, we would compare UTCNOW with the UTC Gametime to determine whether or not to draw the countdown. Along with this change, we would need to modify the UTC Gametime that is retrieved in order to prevent this logic from failing. 

I might roll this back until I have a moment to look at how we're retrieving the gametime.

**Comment by alexanderthebadatcoding** [comment]
I was just focused on fixing the incorrect dates, but It seems to be working for me.

I think in the main renderer file I changed 
```
in def _draw_countdown(self, game):
...
if current_time < game_datetime:
```

and that seemed to fix it for me.

**Comment by alexanderthebadatcoding** [comment]
I'll double check when it gets closer to game time.

**Comment by m0ranwad** [comment]
Sounds good. I might have some time to look at it today.

Adding some debug statements to `__draw_game` made troubleshooting a bit easier for me

```
debug.info(f"Current Time: {current_time}")
debug.info(f"Game Time: {gametime}")
```

**Comment by alexanderthebadatcoding** [comment]
Maybe it's not working haha. I'll keep messing with it.

**Comment by m0ranwad** [comment]
@alexanderthebadatcoding  - I think I found a simple fix. About to post the PR

**Pull request merged**
